config/routes.rb
Rails.application.routes.draw do
  # root :to => 'static_pages#index'
  #get 'events/index'
  # get 'static_pages/index'
  root to: "events#index"
  get 'static_pages/secret'
  resources :events
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!, only: [:secret]
  def index
  end

  def secret
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/events/index.html.erb
<!doctype html>
<html>


<body>
    <main role="main">

      <!-- Main jumbotron for a primary marketing message or call to action -->
      <div class="jumbotron">
        <div class="container">
          <h1 class="display-3">Events</h1>
        </div>
      </div>

      <div class="container">
        <div class="row">
          <% @events.each do |event| %>
            <div class="col-md-4">
              <h2><%= event.title %></h2>
              <p><%= event.description %></p>
              <p><a class="btn btn-secondary" href="<%= event_path(event) %>" role="button">View details &raquo;</a></p>
            </div>
          <% end %>
        </div>

        <hr>

      </div> <!-- /container -->

    </main>
</body>

</html>

app/views/events/new.html.erb
      <div class="jumbotron">
        <div class="container"><h1>under construction</h1>
         </div>
        </div>

      <div class="container">
        <div class="row">

            <div class="col-md-4">
<img src="https://media.giphy.com/media/xT0xewY8zwC6bva1pK/giphy.gif">

            </div>
        </div>
        </div>

app/views/events/show.html.erb
      <div class="jumbotron">
        <div class="container"><h1>un event !</h1>
         </div>
        </div>

      <div class="container">
        <div class="row">

            <div class="col-md-4">
              <h2><%= @event.title %></h2>
              <p><%= @event.description %></p>
              <p><a class="btn btn-secondary" href="<%= event_path(@event) %>" role="button">View details &raquo;</a></p>
            </div>
        </div>
        </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventbride</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

  </head>

  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="/">Events</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "Créer un évenement", new_event_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">S'inscrire / Se connecter</a>
          <div class="dropdown-menu" aria-labelledby="dropdown01">
            <% if !current_user %>
              <%= link_to "S'inscrire", new_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Se connecter", new_user_session_path, class: "dropdown-item" %>
            <% else %>
              <%= link_to "Mon profile", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Se déconnecter", destroy_user_session_path, class: "dropdown-item" %>
            <% end %>
          </div>
        </li>
      </ul>
    </div>
  </nav>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/index.html.erb
<ul>
  <% if user_signed_in? %>
    <li>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    </li>

    <li>
      Voici ton email : <%= current_user.email %>
    </li>

    <li>
      <%= link_to "Secret page", static_pages_secret_path %>
    </li>

    <li>
      <%= link_to "Edit email / password", edit_user_registration_path %>
    </li>

  <% else %>
    <li>    
      <%= link_to "Sign in", new_user_session_path %>
    </li>

    <li>
      <%= link_to "Sign up", new_user_registration_path %>
    </li>

  <% end %>
</ul>

app/views/static_pages/secret.html.erb
<h1>StaticPages#secret</h1>
<p>Find me in app/views/static_pages/secret.html.erb</p>